- hosts: localhost
  vars:
    ssh_key: "id_ed25519"
    source_key: "./.ssh/{{ ssh_key }}"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/{{ ssh_key }}"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: tasks/dotfiles.yml
