---
- name: Play for local workstation
  hosts: localhost

  roles:
    - { role: stow, tags: ["terminal"] }
    - { role: eurkey, tags: ["terminal"] }
    - { role: starship, tags: ["terminal"] }
    - { role: zsh, tags: ["terminal"] }
