- name: "[darwin] Git Submodule Update"
  git:
    repo: git@github.com:jonasdiemer/EurKEY-Mac.git
    dest: ../files/macos
    recursive: yes
    update: yes
    version: master
  tags: eurkey

- name: "[darwin] Copy EurKEY files to /Library/Keyboard Layouts"
  copy:
    src: '{{item}}'
    dest: /Library/Keyboard Layouts
    link: true
  loop:
    - ../files/macos/EurKEY.keylayout
    - ../files/macos/EurKEY.icns
  tags: eurkey