- name: "[darwin] Git Submodule Update"
  ansible.builtin.git:
    repo: git@github.com:jonasdiemer/EurKEY-Mac.git
    dest: ../files/macos
    recursive: yes
    update: yes
    version: master
  tags: eurkey

- name: "[darwin] Copy EurKEY files to /Library/Keyboard Layouts"
  ansible.builtin.file:
    src: "{{ item }}"
    dest: /Library/Keyboard Layouts
    state: link
  loop:
    - ../files/macos/EurKEY.keylayout
    - ../files/macos/EurKEY.icns
  tags: eurkey
