- name: "[darwin] Copy EurKEY files to /Library/Keyboard Layouts"
  ansible.builtin.file:
    src: "{{ item }}"
    dest: /Library/Keyboard Layouts
    state: link
  loop:
    - macos/EurKEY.keylayout
    - macos/EurKEY.icns
  tags: eurkey
