- name: "[darwin] Copy EurKEY Layout to /Library/Keyboard Layouts"
  become: true
  ansible.builtin.copy:
    src: EurKEY.keylayout
    dest: /Library/Keyboard Layouts/EurKEY.keylayout
    mode: 0644
  tags: eurkey

- name: "[darwin] Copy EurKEY Icons to /Library/Keyboard Layouts"
  become: true
  ansible.builtin.copy:
    src: EurKEY.icns
    dest: /Library/Keyboard Layouts/EurKEY.icns
    mode: 0644
  tags: eurkey
