- name: "[darwin] Copy EurKEY Layout to /Library/Keyboard Layouts"
  ansible.builtin.file:
    src: EurKEY-Mac/EurKEY.keylayout
    dest: /Library/Keyboard Layouts/EurKEY.keylayout
    state: link
  tags: eurkey

- name: "[darwin] Copy EurKEY Icons to /Library/Keyboard Layouts"
  ansible.builtin.file:
    src: EurKEY-Mac/EurKEY.icns
    dest: /Library/Keyboard Layouts/EurKEY.icns
    state: link
  tags: eurkey
