- name: Install Kitty Terminal
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin \
    dest=~/.local/stow
  tags:
    - install
    - terminal
    - kitty

- name: Stow Kitty Terminal
  shell: cd ~/.local/stow && stow -v kitty.app
  tags:
    - install
    - terminal
    - kitty
