---
- name: "[darwin] Install zsh"
  community.general.homebrew:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-completions
    state: present
  tags: zsh

- name: "[darwin] Set zsh as default shell"
  ansible.builtin.command: chsh -s /opt/homebrew/bin/zsh
  changed_when: false
  tags: zsh
