---
- name: "[darwin] Register current user (workaround to change default shell)"
  ansible.builtin.command: whoami
  changed_when: false
  register: current_user
  tags: zsh

- name: "[darwin] Register zsh path"
  ansible.builtin.command: which zsh
  changed_when: false
  register: zsh_path
  tags: zsh

- name: "[darwin] Change default shell to zsh"
  become: true
  ansible.builtin.command: "chsh -s {{ zsh_path.stdout }} {{ current_user.stdout }}"
  changed_when: false
  tags: zsh
