---
- name: "[debian] Install zsh"
  ansible.builtin.package:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-completions
    state: present
  tags: zsh

- name: "[debian] Set zsh as default shell"
  ansible.builtin.command: chsh -s $(which zsh)
  changed_when: false
  tags: zsh
