- name: "[main] Include tasks for {{ ansible_os_family }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  tags: kitty

- name: "[main] Stow Kitty"
  ansible.builtin.command: "cd {{ ansible_env.HOME }}/.dotfiles && stow kitty"
  changed_when: false
  tags: kitty
