---
- name: Install Homebrew.
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  when: ansible_os_family == 'Darwin'

- name: Print Homebrew prefix.
  ansible.builtin.command:
    cmd: brew --prefix
  register: brew_prefix
  changed_when: false
  when: ansible_os_family == 'Darwin'

- name: Set Homebrew prefix as fact.
  ansible.builtin.set_fact:
    brew_prefix: "{{ brew_prefix.stdout }}"
  when: ansible_os_family == 'Darwin'
